### ISSUE TITLE
Unit testing : refactoring

### ISSUE THREAD

**Issue by marg51** [kentcdodds/ux-genie#7]
Hi,

At the moment, the directiveSpec is empty. The problem is, it will be hard to test the application because there is two big directives, and directives aren't the easiest part when dealing with unit testing. 

So, what could be done ?

IMO, The first thing to do is to move the functions from the directives to their own controller (ie : _uxLampCtrl_ and _genieWishCtrl_ ), it will be, by far, easier to test. 

I started to do it, but it will take some time. I want to be sure that you are even interested, with this solution or another. 

And what about splitting uxGenie.js into multiple files to improve readability ? ( it could be _directives.js / controllers.js_ or _uxLamp.js / genieWish.js_ )

Cheers.

**Comment by kentcdodds** [comment]
That sounds great to me. I would love to see it tested and become more modular. We'd need to make a build to concatenate the files into a single file for distribution.
Thanks for your interest in the project! I'd love to see what you come up with. Out of curiosity, are you using genie?

**Comment by marg51** [comment]
I'm not using it for now, but it's interesting and I may need it in a quite large project. 
Do you have any pref for the build tool ?

**Comment by kentcdodds** [comment]
The genie project uses grunt. I'm interested in learning gulp. So I'd be happy with either. Thanks! :-)

**Comment by marg51** [comment]
I'm interested in learning gulp, too. I'll see what I can do. Anyway, it's not for today. No promise so far.

**Comment by kentcdodds** [comment]
That's fine. Thanks for anything you can do to help.
